blog/urls.py
from django.urls import path, include

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('blog/<int:blog_id>', views.view_post, name='blog'),
    path('blog/create', views.create_blog, name='create_blog'),
    path('register', views.register_user, name='register_user'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('blog.urls'))
]

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

class User(AbstractUser):
    pass

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    blog_title = models.CharField(max_length=200)
    blog_text = models.TextField()
    pub_date = models.DateTimeField('date published')
    mod_date = models.DateTimeField('date modified', null=True, blank=True)
    private = models.BooleanField(default=False)

    def __str__(self):
        return self.blog_title

blog/forms.py
from django import forms
from datetime import date

class BlogForm(forms.Form):
    title = forms.CharField(label='Blog title', max_length=200, min_length=3, strip=True)
    content = forms.CharField(label='Content', widget=forms.Textarea, strip=True, required=False)
    pub_date = forms.DateField(label='Publishing date', widget=forms.SelectDateWidget, required=False, initial=date.today)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import generic
from blog.models import Blog, User
from django.utils import timezone
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib import messages
from django.urls import reverse
from blog.forms import BlogForm

def index(request):
    curr_blog = Blog.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:1]
    previous = None
    next = None
    if curr_blog:
        previous = Blog.objects.filter(pub_date__lt=curr_blog[0].pub_date).order_by('-pub_date')[:1]
        next = Blog.objects.filter(pub_date__lte=timezone.now()).filter(pub_date__gt=curr_blog[0].pub_date).order_by('pub_date')[:1]

    context = {
        'curr_blog': curr_blog, 
        'previous': previous,
        'next': next,
        }

    return render(request, 'index.html', context)

def view_post(request, blog_id):
    curr_blog = Blog.objects.filter(id=blog_id).filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:1]
    previous = None
    next = None
    if curr_blog:
        previous = Blog.objects.filter(pub_date__lt=curr_blog[0].pub_date).order_by('-pub_date')[:1]
        next = Blog.objects.filter(pub_date__lte=timezone.now()).filter(pub_date__gt=curr_blog[0].pub_date).order_by('pub_date')[:1]

    context = {
        'curr_blog': curr_blog, 
        'previous': previous,
        'next': next,
        }

    return render(request, 'index.html', context)

def create_blog(request):
    if request.method == 'POST':
        form = BlogForm(request.POST)
    else:
        form = BlogForm()
    return render(request, 'blog/create.html', {'form': form})

def register_user(request):

    class CustomUserCreationForm(UserCreationForm):

        class Meta(UserCreationForm.Meta):
            model = User
            fields = UserCreationForm.Meta.fields
            help_texts = {
                'username': None,
            }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['password1'].help_text = None

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, 'Registration successful!')
            login(request, user)
            messages.info(request, 'Login successful, welcome {}!'.format(user.username))
            return redirect('blog:index')
    else:
        form = CustomUserCreationForm()
    return render(request, 'registration/register.html', {'form': form})

blog/templates/base.html
<!DOCTYPE html>
<html lang=en>
    <head>
        <meta charset="utf-8">
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/skeleton.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/local.css' %}">
        <title>Djangoblog - {% block title %}{% endblock %}</title>
        <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="navbar">
            {% for navlink in navigation %}
            {% if navlink.2 %}
            <a href="{% url navlink.1 %}">{{ navlink.0 }}</a>
            {% elif navlink.3 == user.is_authenticated %}
                {% if not navlink.4 %}
                <a href="{% url navlink.1 %}">{{ navlink.0 }}</a>
                {% elif navlink.4 == perms.blog.add_blog %}
                <a href="{% url navlink.1 %}">{{ navlink.0 }}</a>
                {% endif %}
            {% endif %}
            {% endfor %}
        </div>        
        <div id="content">
            <div class="row">
                <div class="two columns" style="margin-top: 30px"></div>
                <div class="six columns" style="margin-top: 30px">
                    {% if messages %}
                        <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                    {% block content %}{% endblock %}
                </div>
                <div class="four columns" style="margin-top: 30px"></div>
            </div>
        </div>
    </body>
</html>

blog/templates/blog/create.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
err
{% endif %}

<form method="post" action="{% url 'blog:create_blog' %}">
{% csrf_token %}
<table>
    {{ form }}
</table>

<input type="submit" value="Create">
</form>

{% endblock %}

blog/templates/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
{% if curr_blog %}
{# with latest_blogs|first as curr_blog #}
<h1>{{ curr_blog.0.blog_title }}</h1>
<div>Date: {{ curr_blog.0.pub_date }}</div>
<div>Author: {{ curr_blog.0.author }}</div>
{{ curr_blog.0.blog_text|linebreaks }}
{# endwith #}
    {# if curr_blog.get_next_by_pub_date #}
    {% if next %}
    Next: <a href="{% url 'blog:blog' next.0.id %}">{{ next.0 }}</a>
    {% endif %}
    {# if curr_blog.get_previous_by_pub_date #}
    {% if previous %}
    Previous: <a href="{% url 'blog:blog' previous.0.id %}">{{ previous.0 }}</a>
    {% endif %}
{% else %}
<div>No content yet.</div>
{% endif %}
{% endblock %}